apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv
  namespace: dv-sys
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # Use the /data folder as other directories may be lost on minikube restart
    path: "/home/es-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data-pvc
  namespace: dv-sys
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: dv-sys
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.8.0
          # args:
          #   - manager
          #   - --log-verbosity=1
          # resources:
          #   limits:
          #     cpu: 1000m
          #   requests:
          #     cpu: 100m
          env:
            - name: discovery.type
              value: single-node
            - name: logger.org.elasticsearch.discovery
              value: DEBUG
            # - name: ES_JAVA_OPTS
            #   value: "-Xms512m -Xmx512m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
              # name: client
          # - containerPort: 9300
          # name: nodes
          volumeMounts:
            # will store data for db
            - mountPath: "/usr/share/elasticsearch/data"
              name: es-storage-data
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: es-storage-data
              mountPath: /usr/share/elasticsearch/data
        # - name: increase-vm-max-map
        #   image: busybox
        #   command: ["sysctl", "-w", "vm.max_map_count=262144"]
        #   securityContext:
        #     privileged: true
        # - name: increase-fd-ulimit
        #   image: busybox
        #   command: ["sh", "-c", "ulimit -n 65536"]
        #   securityContext:
        #     privileged: true
      volumes:
        - name: es-storage-data
          persistentVolumeClaim:
            claimName: es-data-pvc
      # securityContext:
      #   fsGroup: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: dv-sys
  labels:
    service: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
      # nodePort: 9200
  selector:
    app: elasticsearch
